### ISSUE TITLE
Incompatible with Laravel 5.2

### ISSUE THREAD

**Issue by driade** [spatie/laravel-missing-page-redirector#10]
Hello, good afternoon.

The package seems to be incompatible with Laravel 5.2. Should it?

Thanks!

**Comment by freekmurze** [comment]
There were some breaking changes regarding collection methods in L5.3. At our company we only use L5.3 for project, so it makes no sense for us anymore to provide compatibility with something lower than that version.

Feel free to fork the code and maintain your own version.

**Comment by driade** [comment]
Thanks!
