### ISSUE TITLE
Unused optional parameters

### ISSUE THREAD

**Issue by nckg** [spatie/laravel-missing-page-redirector#16]
When you call `/old-blog` with following configuration `/old-blog/{url?} => '/new-blog/{url}'`, you will be redirected to `/new-blog/{url}` when I was expecting to see `/new-blog`.
 Is this expected behaviour?

Thanks!

**Comment by freekmurze** [comment]
Could you try adding a `/old-blog` to  `/new-blog` rule?

**Comment by nckg** [comment]
Oh yes, that works 😄 . Should have thought of this myself...

**Comment by freekmurze** [comment]
👌
