### ISSUE TITLE
Not redirecting

### ISSUE THREAD

**Issue by gizburdt** [spatie/laravel-missing-page-redirector#21]
Hi,

Awesome package! But it's not redirecting 404 pages. I debugged some code with `dd`s. Looks good for most of the code. But here it returns null: https://github.com/spatie/laravel-missing-page-redirector/blob/master/src/RedirectsMissingPages.php#L19, while it contains an array here: https://github.com/spatie/laravel-missing-page-redirector/blob/master/src/Redirector/ConfigurationRedirector.php#L11

Thanks :)

**Comment by sebastiandedeyne** [comment]
Could you replace `bind` with `singleton` here and see if it helps?

https://github.com/spatie/laravel-missing-page-redirector/blob/b1652cef4f66fdd449fc41aa3c65321ea0bd32e6/src/MissingPageRedirectorServiceProvider.php#L20

**Comment by gizburdt** [comment]
Unfortunately that doesn't work :(

**Comment by sebastiandedeyne** [comment]
You could try throwing the exception here instead of catching it

https://github.com/spatie/laravel-missing-page-redirector/blob/b1652cef4f66fdd449fc41aa3c65321ea0bd32e6/src/MissingPageRouter.php#L44

Otherwise, hard to say what's going on without any config & example url that doesn't work. Maybe you could spin up a fresh Laravel app and create a broken example with fake urls?

**Comment by gizburdt** [comment]
It works :) I misinterpreted this example:

```php
'redirects' => [
       '/old-blog/{url}' => '/new-blog/{url}',
],
```

Thought, {url} was a kind of wildcard, but it's model  binding I think? The thing I would like to do is every url starting with /cms/ to redirect to the same url, but then without the /cms/ part. I found this will work: ` '/cms/*' => '/*',`

Thanks again :)

**Comment by gizburdt** [comment]
I think the redirect was cached: `'/cms/*' => '/*'` doesn't work. Do you have a solution for my problem? Redirect 404 pages starting with /cms/ redirect to same url without /cms/?

**Comment by sebastiandedeyne** [comment]
This package is better suited for sealing with multiple, specific redirects. If you only need to do one catch-all wildcard redirect, I'd suggest not using this package.

You could write your own route, and add a catch-all regex to the parameter:

```php
Route::get('/cms/{url?}', function () {
    return redirect()->to(/* substring the request path here or something  similar */);
})->where('url', '.*');
```

**Comment by gizburdt** [comment]
Thanks :)
