### ISSUE TITLE
implementing missings rediretors

### ISSUE THREAD

**Issue by MahdiPishguy** [spatie/laravel-missing-page-redirector#40]
my missing ulr is:
http://127.0.0.1:8000/showContent/aboutUs

and correct of that is:
http://127.0.0.1:8000/en/showContent/aboutUs

how can i resolve that?

route:

```
Route::group(['middleware' => 'missingRedirects'], function () {
    Route::get('/showContent/aboutUs','HomeController@showAboutUsPage');
});
```

kernel.php

    protected $routeMiddleware = [
        'missingRedirects'=>\Spatie\MissingPageRedirector\RedirectsMissingPages::class,
        'checkAdmin' => \App\Http\Middleware\CheckAdminAuthenticated::class,
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];

and then `missing-page-redirector.php`:

    'redirects' => [
        '/showContent/aboutUs'=>'/fa/showContent/aboutUs',
    ],

**Comment by introwit** [comment]
Hey can you explain your question a bit more? What specifically do you want to achieve so we can help you out.

**Comment by ultrono** [comment]
@MahdiPishguy Are you referring to redirecting to an url with a variable i.e. the current locale?

**Comment by freekmurze** [comment]
If you want to redirect to `/en/showContent/aboutUs`, it seems like you have a typo in your code.

Use this in the config file:

```php
'redirects' => [
    '/showContent/aboutUs'=>'/en/showContent/aboutUs',
],
```

If you want to use a variable in your redirect take a look at [creating your own redirector](https://github.com/spatie/laravel-missing-page-redirector#creating-your-own-redirector).
