### ISSUE TITLE
preg_replace(): Compilation failed:

### ISSUE THREAD

**Issue by Daikazu** [spatie/laravel-missing-page-redirector#48]
I'm getting the Exception error `preg_replace(): Compilation failed: range out of order in character class at offset 6` no matter what my config redirects are. This results in a `RedirectNotFound` and my 404 page is shown.

example config
```php
redirects' => [
        '/articles/' => '/blog'
    ],
```

After Digging around in the code I found that it's related to the line `$redirectUrl = preg_replace('/\/{[\w-_]+}/', '', $redirectUrl);` of the `resolveRouterParameters` function of the `MissingPageRouter` class.
When I comment that line out everything works as expected. My regex knowledge is small and i'm not sure exactly what that line is suppose to do. 

I couldn't find any previous issues that seem to have the same problem. Maybe someone will have some insight.

**Comment by Daikazu** [comment]
My bad, I was playing around with the code and didn't undo enough times before I copied and pasted. I edited my initial post to reflect the corrected line of code. 

I was only able to see the warning by trapping it with a try catch. 

The whole reason I started digging into this was that I cannot for the life of me get this to work with a clean install. I always get a 404 response unless I comment out that line

**Comment by Daikazu** [comment]
Okay I figured it out so it turns out that there are some changes to the preg  library used in PHP 7.3. [(PHP :: Bug #77334)](https://bugs.php.net/bug.php?id=77334)

Since `\w` matches any word character (equal to [a-zA-Z0-9_]) you could simplify the expression to just `/\/{[\w-]+}/` and this should work the same and doesn't appear to error in PHP 7.3.

**Comment by freekmurze** [comment]
Thanks for the report and the PR!
