### ISSUE TITLE
redirect url with optional paremeters to query string

### ISSUE THREAD

**Issue by mojtabaRKS** [spatie/laravel-missing-page-redirector#52]
hello ! 
i have this url : 

`www.website.com/category/product/page/{numberOfPage}`

how to redirect to this url : 

`www.website.com/category/product?page={numberOfPage}`

thanks for your answer :)

**Comment by atymic** [comment]
Based on the code here:
https://github.com/spatie/laravel-missing-page-redirector/blob/master/src/MissingPageRouter.php#L75-L77

Have you tried the following?
```
www.website.com/category/product?page={{numberOfPage}}
```
