### ISSUE TITLE
Need to query database for new url redirect

### ISSUE THREAD

**Issue by jrson83** [spatie/laravel-missing-page-redirector#61]
How can I redirect to a parameter if the parameter doesn't exist in the old URL?
I need to redirect:

`/labels/{name}` to `/label/{id}/{name}`

I could use the `name` from the old URL to get the ID from the database inside a controller, but I don't understand `Creating your own redirector` chapter. Does this mean to create a controller?

Can you please give an example of a custom controller to select from the database?

**Comment by SamuelNitsche** [comment]
I think this could help you.

https://github.com/spatie/freek.dev/blob/master/app/Services/MissingPageRedirector/LegacyUrlsRedirector.php

**Comment by jrson83** [comment]
Thanks, I gonna look into this. For now I created all redirects manually.
