### ISSUE TITLE
Database instead of config file

### ISSUE THREAD

**Issue by timmoh** [spatie/laravel-missing-page-redirector#65]
Is there an Option to use a database table for redirect?

so instead of
```
'redirects' => [
//        '/non-existing-page' => '/existing-page',
//        '/old-blog/{url}' => '/new-blog/{url}',
    ],
```
use DB Tables/Model

**Comment by freekmurze** [comment]
You can create your own redirector class that use the DB: https://github.com/spatie/laravel-missing-page-redirector#creating-your-own-redirector
