### ISSUE TITLE
Problems with redirecting

### ISSUE THREAD

**Issue by alibaba258** [spatie/laravel-missing-page-redirector#74]
Hi,

first of all thank you very much for your awesome packages. 

I have tried this package but get an error. My redirected route is a Livewire component. I found Issue #73 and tried to redirect to a normal site. It´s still the same error. I´m using Laravel 8.56.0 Livewire 2.8.1, plugin verison 2.7.3 and PHP 8.0. Any ideas whats going on wrong here? Or did i made a mistake?

Thanks for your support 

`Symfony\Component\HttpFoundation\Response::setContent(): Argument #1 ($content) must be of type ?string, Livewire\Redirector given, called in C:\xampp\htdocs\hofladen\vendor\laravel\framework\src\Illuminate\Http\Response.php on line 72`

**Comment by alibaba258** [comment]
Update: 
Works now. Need to remove the global livewire route and replaced it with a normal Controller Route.

**Comment by edstevo** [comment]
I have this problem and I am received this error:

`Symfony\Component\HttpFoundation\Response::setContent(): Argument #1 ($content) must be of type ?string, Livewire\Features\SupportRedirects\Redirector given, called in /Users/edstevo/Sites/flowflex/ffx-laravel/vendor/laravel/framework/src/Illuminate/Http/Response.php on line 73`

Is there any plan to have this package work with Laravel Volt?
