### ISSUE TITLE
Method Illuminate\Support\Str::of does not exist

### ISSUE THREAD

**Issue by chrisGeonet** [spatie/laravel-missing-page-redirector#75]
Starting in v2.9.1 you are using Str::of method in MissingPageRouter.php.
This is available only starting from Laravel 7.

I have this package installed in a Laravel 6 site. Composer has updated this package to 2.9.1. No compatibility warnings were shown, but the package no longer works.

**Comment by freekmurze** [comment]
O whoops, if you need a quick fast, could you PR that fixes it in Laravel 6?

**Comment by chrisGeonet** [comment]
Ok, I've done a PR. I hope I've done it right.

**Comment by freekmurze** [comment]
Thanks!

**Comment by chrisGeonet** [comment]
It broke. Updated code ready for review
