### ISSUE TITLE
Laravel v9.33.0 not working

### ISSUE THREAD

**Issue by it-can** [spatie/laravel-missing-page-redirector#77]
Seems this package is not working with the latest Laravel 9.33.0, I think it has to do with this PR https://github.com/laravel/framework/pull/44339

All tests seem to fail on the latest version, rolling back to laravel/framwork v9.32.0 and this package is working again...

**Comment by it-can** [comment]
As far as I can tell the "problem" is here:

https://github.com/spatie/laravel-missing-page-redirector/blob/main/src/MissingPageRouter.php#L42

it seems that  ```$redirects``` is null on v9.33.0 (9.32 it is filled correctly)

**Comment by it-can** [comment]
Okay think I found the "problem"

https://github.com/laravel/framework/commit/103ae1e4c83682b22f7eb6b8778e1c4e2f854d75#diff-efe2a07687b9b821bbd99ae38a9329253f032e6df04bdea02bba9303a2b2bead

if I revert those changes then this package works again...

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this (or if the bug is at Laravel, send a bug fix there 🙂)

**Comment by it-can** [comment]
> I'd accept a PR that fixes this (or if the bug is at Laravel, send a bug fix there 🙂)

The changes recently made are too complex for me to completely understand…
